# Generated by Django 6.0.2 on 2026-02-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='left_bans_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='left_picks_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='right_bans_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='right_picks_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchdraftaction',
            name='target_side',
            field=models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], default=None, max_length=5),
            preserve_default=False,
        ),
    ]
