# Generated by Django 6.0.2 on 2026-02-04 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_match_left_bans_confirmed_match_left_picks_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['round_index', 'match_index']},
        ),
        migrations.AddField(
            model_name='match',
            name='match_index',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='core.match'),
        ),
        migrations.AddField(
            model_name='match',
            name='next_side',
            field=models.CharField(blank=True, choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='round_index',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('tournament', 'round_index', 'match_index')},
        ),
    ]
