# Generated by Django 5.2.11 on 2026-02-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_matchdraftaction_is_locked_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchdraftaction',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='matchdraftaction',
            unique_together=set(),
        ),
    ]
