# Generated by Django 5.2.11 on 2026-02-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_boss_id_alter_bosstime_id_alter_match_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bosstime',
            options={'ordering': ['best_time_ms']},
        ),
        migrations.RenameField(
            model_name='match',
            old_name='left_time_seconds',
            new_name='left_time_ms',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='right_time_seconds',
            new_name='right_time_ms',
        ),
        migrations.RemoveField(
            model_name='bosstime',
            name='best_time_seconds',
        ),
        migrations.AddField(
            model_name='bosstime',
            name='best_time_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
