# Generated by Django 5.2.11 on 2026-02-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_bosstime_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchdraftaction',
            options={'ordering': ['step_index']},
        ),
        migrations.AddConstraint(
            model_name='matchdraftaction',
            constraint=models.UniqueConstraint(fields=('match', 'step_index'), name='uniq_matchdraftaction_match_step'),
        ),
        migrations.AddConstraint(
            model_name='matchdraftaction',
            constraint=models.UniqueConstraint(fields=('match', 'action_type', 'slot_index', 'acting_side'), name='uniq_matchdraftaction_slot_per_side'),
        ),
    ]
