# Generated by Django 5.2.11 on 2026-02-10 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_matchdraftaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player_left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_left', to='core.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_right', to='core.player'),
        ),
    ]
